# Generated by scripts/render-homebrew.mjs on each release — do not edit by hand.
# Source template: packaging/homebrew/verql.cask.rb.tmpl in arshad-shah/verql.
# Only the version and the two dmg sha256s are filled per release; the URLs use
# Ruby interpolation of `version` and match electron-builder's lowercase output
# (verql-<version>-<arch>.dmg).
cask "verql" do
  version "1.6.0"

  on_arm do
    sha256 "e6135154b3dd0719b2762a93bdb2f9080db64de5675a0aca8089fa3e9590f962"
    url "https://github.com/arshad-shah/verql/releases/download/v#{version}/verql-#{version}-arm64.dmg",
        verified: "github.com/arshad-shah/verql/"
  end

  on_intel do
    sha256 "5ca2bf53e821cefe2716f1a1e6cc60b1789916ec0138e53a212b351239911605"
    url "https://github.com/arshad-shah/verql/releases/download/v#{version}/verql-#{version}-x64.dmg",
        verified: "github.com/arshad-shah/verql/"
  end

  name "Verql"
  desc "Fast, extensible desktop database client"
  homepage "https://github.com/arshad-shah/verql"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates false
  depends_on macos: ">= :ventura"

  app "Verql.app"

  # Verql is currently distributed unsigned. Homebrew normally just flips the
  # quarantine flag to "approved", but macOS Sequoia (15+) still rejects the
  # bundle from Finder/Spotlight ("Verql is damaged"). Strip the attribute
  # outright so Gatekeeper never re-evaluates the bundle on launch.
  # Remove this block once we ship signed + notarised builds.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Verql.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Application Support/Verql",
    "~/Library/Logs/Verql",
    "~/Library/Preferences/com.electron.verql.plist",
    "~/Library/Saved Application State/com.electron.verql.savedState",
  ]
end
