# Generated by scripts/render-homebrew.mjs on each release — do not edit by hand.
# Source template: packaging/homebrew/verql.formula.rb.tmpl in arshad-shah/verql.
# Only the version and the AppImage sha256 are filled per release; the URL uses
# Ruby interpolation of `version` and matches electron-builder's lowercase output
# (verql-<version>-x86_64.AppImage).
#
# Linux install path: `brew` on Linux has no casks, so the GUI app ships as a
# formula that installs the AppImage plus a `verql` launcher shim on PATH.
class Verql < Formula
  desc "Fast, extensible desktop database client"
  homepage "https://github.com/arshad-shah/verql"
  version "1.8.1"
  url "https://github.com/arshad-shah/verql/releases/download/v#{version}/verql-#{version}-x86_64.AppImage"
  sha256 "ab63b843e00a78a9c1145e7ad1236099cb9d69622a0b9c0ae0aa3b10d3f5f482"
  license "MIT"

  # AppImages are self-contained; they only need a FUSE runtime at launch.
  depends_on :linux

  def install
    # Homebrew downloads the URL into the staging dir under its basename.
    appimage = "verql-#{version}-x86_64.AppImage"
    libexec.install appimage => "verql.AppImage"
    chmod 0755, libexec/"verql.AppImage"

    (bin/"verql").write <<~SH
      #!/bin/bash
      exec "#{libexec}/verql.AppImage" "$@"
    SH
  end

  test do
    assert_path_exists libexec/"verql.AppImage"
  end
end
